name: simple_navigation_menu
description: A library to help you use a simple and clean navigation menu.
version: 0.1.4
homepage: https://github.com/lopb/simple_navigation_menu
repository: https://github.com/lopb/simple_navigation_menu
issue_tracker: https://github.com/lopb/simple_navigation_menu/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
